version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    environment:
    - DEBUG=1
    - DEFAULT_REGION=eu-west-1
    ports:
    - '4566-4583:4566-4583'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock